apiVersion: apps/v1
kind: Deployment
metadata:
  name: alps
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: alps
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
